name: firebase_login_demo
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  #  https://pub:dev/packages/bloc
  bloc: ^3.0.0

  #  https://pub:dev/packages/flutter_bloc
  flutter_bloc: ^3.2.0

  #  https://pub:dev/packages/equatable
  equatable: ^1.1.1

  #  https://pub:dev/packages/cloud_firestore
  cloud_firestore: ^0.13.4+2

  #  https://pub:dev/packages/firebase_auth
  firebase_auth: ^0.15.5+3

  #  https://pub:dev/packages/google_sign_in
  google_sign_in: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/