name: state_management
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#for flutter vaniila bloc - using RxDart
  #  rxdart: ^0.23.1

#for flutter bloc
  #  https://pub:dev/packages/bloc
  bloc: ^3.0.0

  #  https://pub:dev/packages/flutter_bloc
  flutter_bloc: ^3.2.0

#for flutter redux
  # https://pub.dev/packages/flutter_redux
  flutter_redux: ^0.6.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true